### ISSUE TITLE
Require Ability to Set Location for ATC/AWACS/CA

### ISSUE THREAD

**Issue by Eddie686** [ciribob/DCS-SimpleRadioStandalone#157]
At present there is no system to set a location within the world for ATC/AWACS panel users, this means that when the use of this panel is required distance and LOS limitations must be disabled.

Add a method of setting a location for ATC/AWACS/CA clients. Suggest allowing either geographic coordinates (system used by UniversRadio & Aries radio) or, if possible, a unit within the mission by name. 

To allow for AWACS, transmitter altitude should also be configurable.

For specific cases it may be useful to allow the setting of multiple antenna locations. For example, within the NTTR, the Blackjack controlling agency has multiple ground based antennas to cover the NTTR area.

**Comment by ciribob** [comment]
I've been thinking about this as well, both Aries & UniversRadio have a "shadow map" which is a (possibly low res?) export of the entire DCS map. As such they can pull co-ordinates direct from that.

SRS works differently but I should be able to add something where you enter co-ordinates in some format (likely lat long) and it gives you a DCS position which you input. Extending to a specific unit is trickier as you dont get all units positions due to export limitations

I'll add to the list though :)

**Comment by ciribob** [comment]
Closing and moving to #355
