### ISSUE TITLE
Feature Request:  Channel Presets + Preset Hotkeys

### ISSUE THREAD

**Issue by ghostots** [ciribob/DCS-SimpleRadioStandalone#176]
Hi ciribob, my request is as follows:

Please add configurable channel presets.   Almost every modern radio has them, and it's a pretty huge deal for using this in-game with FC3 modules (or anything that has an incomplete radio simulation).

The way I envision this working is as follows:

The application makes one or two hotkeys available (channel up, channel down)
The player sets up a small file containing presets as a key-value pair:

1=223.0
2=290.950
3=195.5

... etc.  I know it gets tricky if you have to deal with multiple radio types, so presets could be under 'radio type' headers if desired, such as:

radio=ARC-210
1=223.0
2=290.950
3=195.5

etc.

**Comment by ciribob** [comment]
Meant to write this as a ticket already :)

I'm going to go with basic text files that are named after the radio you want to set presets for

Presets will be loaded when connecting to a server but there will also be a reload button and/or a option  to load specific file or reload the text file if you want to. 

Does that sound ok?

I prefer per radio to per aircraft as i think people will get confused creating the presets otherwise

**Comment by ghostots** [comment]
That sounds great to me :)

**Comment by ciribob** [comment]
Yes 👍 
Hopefully get this done in the next two weeks depending on time

**Comment by ciribob** [comment]
![wip-channels](https://cloud.githubusercontent.com/assets/786992/25057119/0fde1538-2165-11e7-8a5b-28d7df24e30e.JPG)

Very early WIP

**Comment by ciribob** [comment]
More progress: https://forums.eagle.ru/showpost.php?p=3121232&postcount=1480

**Comment by ghostots** [comment]
That's very good progress, and much appreciated!

**Comment by ciribob** [comment]
Implemented in 1.3.1.0 

https://github.com/ciribob/DCS-SimpleRadioStandalone/releases/tag/1.3.1.0

👍
