### ISSUE TITLE
Hornet Guard monitor

### ISSUE THREAD

**Issue by VKing6** [ciribob/DCS-SimpleRadioStandalone#253]
Is it possible to make the GRCV function on the Hornet radios work? I.e. receive on both the selected channel and the guard channel at the same time?

**Comment by MorpheusXAUT** [comment]
From my understanding (based on the last discussion on the SRS Discord server), there's no way to query the status of the GRCV radio function (since it's basically just a button), so SRS can't really tell what state it is in (and thus sync properly), unfortunately.

**Comment by m4ti140** [comment]
Maybe just make GRCV on for COMM1 by default, regardless of of in-game setting? Since that's how it would be set up anyway?

**Comment by MorpheusXAUT** [comment]
I personally don't really like the idea of having it default on, especially since that wouldn't really solve the issue of SRS not being able to tell the current state of the ingame system, it'd just be the opposite of what it currently is now...
Furthermore, you wouldn't be able to turn it off and would be "forced" to tune to a frequency without the option to leave it should someone decide to use it.

We'll have to see if there's a different way we could handle this (preferably via ingame controls somehow) - if worse comes to worst and we cannot track the ingame state at all, it could also become a setting you can configure via the SRS radio overlay...

**Comment by raffaeleragni** [comment]
If you understand what a guard is and used for, you'd probably rethink that into having it enabled. Or at least configurable from SRS settings?
Guard is pretty important for mission emergencies. And as of right now the hornet cannot listen to SRS guard without sacrificing a radio.

**Comment by syn111** [comment]
Any news on this? The Hornet is missing an important capability in organized MP events of moitoring guard. Is it possible to get a toggable option on the in-game SRS UI at least?

**Comment by ciribob** [comment]
Implemented in next release 1.7.0.1
