### ISSUE TITLE
windows sound "fatal crash" (?) after clicking "yes" to join advised SRS server when switching DCS servers.

### ISSUE THREAD

**Issue by Dani3lNL** [ciribob/DCS-SimpleRadioStandalone#276]
first there is the nice windows 7 sound "dodi?" (friendly sound), then when clicking yes/ok in the window with the advised SRS server, you hear the "BAAAM" fatal error sound for no reason at all... (neither SRS nor DCS crashed)

**Comment by MorpheusXAUT** [comment]
Hi,

SRS plays a Windows system sound (labeled `Hand` by Microsoft), Win10 example [here](https://www.dropbox.com/s/9drucchbjpq8dt5/hand.mp3?dl=0) whenever it performs an autoconnect as an indication a change was made. Unfortunately, the default Windows 10 system sounds only contain a single [differently sounding one](https://www.dropbox.com/s/gqf40ubwdkjnkdb/exclamation.mp3?dl=0), so our selection was pretty limited without adding any other custom, external sounds.
Since I don't have a Win7 computer anymore, I couldn't try the sounds on that OS, but assumed they would sounds at least somewhat similar (or at least not differ as much, with one being the default crash sound). I'll see if I can dig up a Win7 VM somewhere and try the different sounds out there so we can find a better one.

**Comment by Dani3lNL** [comment]
I am on Win 10, I didn't say I'm using Win 7. (this weird old sound-bug makes it feel like I'm still using Windows XP LOL) and the sound I mean is none of the two of your two links.....

**Comment by Dani3lNL** [comment]
(yes, maybe I meant an XP and not 7 sound, I'm not sure)

**Comment by Dani3lNL** [comment]
I think it's  the "Win 10 critical stop" sound that I mean.

**Comment by MorpheusXAUT** [comment]
Ah, sorry, since you talked about a Windows 7 sound being played, I assumed you were running Win7.
Could you get a recording of the sound you're talking about? The only sounds SRS should play are the two listed above (the first one when a connection is established via autoconnect, the second one is triggered by the message box confirming the switch popping up).

**Comment by Dani3lNL** [comment]
Yes I'm quite sure it's that one. It plays after clicking "ok" or "yes" (I forgot) to acknowledge that SRS switches IP to the new DCS server (that the player has joined).

**Comment by MorpheusXAUT** [comment]
Alright, I'll look into it again and see if I can find any reason it's coming up, thanks for the report!

**Comment by MorpheusXAUT** [comment]
Can you consistently reproduce this issue or is there anything to help narrow a potential issue down (e.g. does it only happen on specific servers)?
Just tried all variants of autoconnect I could think of on a local server and only ever heard the sounds expected and mentioned above...
Does your `clientlog.txt` file contain anything of interest?
