### ISSUE TITLE
no feedback on connect with server offline/unreachable.

### ISSUE THREAD

**Issue by giupo** [ciribob/DCS-SimpleRadioStandalone#279]
Steps to reproduce (on `Microsoft Windows [Version 10.0.17134.285]`)
- Open SR-Client
- Set as server address `127.0.0.1`
- click connect

Result:
- Button label sets to "connecting" and sets back to "connect"
- no messages (text, icons) change as side effect

**Comment by ciribob** [comment]
So you'd like an alert box or something more visual indicating the connection failed?

**Comment by MorpheusXAUT** [comment]
@ciribob seems like we missed one (handled) connection error and didn't set the error-flag returned properly, as fixed in #280.
As of now, the connection status indicators do not change at all - the client simply switches from `Connecting` back to `Connect`. PR should fix that, simple oversight of returned flags.

**Comment by ciribob** [comment]
Ah great spot!
