### ISSUE TITLE
Streamer/recorder feature: radio voice effect also on passthrough?

### ISSUE THREAD

**Issue by magwo** [ciribob/DCS-SimpleRadioStandalone#285]
There is no radio voice effect applied on the passthrough (mic output)?

I think this would be a desirable feature for streamers/recorders trying to record a full event with all comms on SRS, including the "radio voice" of the player running the stream/recording.

Or is this already doable? As far as I can tell, the mic passthrough results in normal voice, but with gain applied.

**Comment by MorpheusXAUT** [comment]
Hi @magwo,

correct, we do not apply any radio effects to the mic pass-through output.
This is mainly due to the fact that SRS does not have any effect distorting the _recording_ of your voice (for instance caused by the quality of the recording mic or other environment sounds), but only apply an effect on the _receiving_ radio (which is calculated based on distance/interference).
For this reason, applying SRS' radio effect to the mic output would not change anything in the "simulation" we try to achieve - you won't have distance-based distortion in your local recording anyways.
Unfortunately, since we only apply "incoming" radio effects at the moment, I fear there's not much to add in terms of locally-recorded effects.

**Comment by thebgpikester** [comment]
UR has this, and you can use a virtual audio cable and send modulated voice to it for streaming. I'm not sure how it calculates the voice modulation then, if it goes nowhere, probably it's a cheaper effort.

I guess this is a limitation of SRS then?

**Comment by MorpheusXAUT** [comment]
With the current handling of radio effects in SRS, this is somewhat limited, yeah.

The effects are a client-side setting in SRS, so everyone can choose to enable or disable them depending on their preferences. Since we apply all radio effects at the same place when receiving audio from other clients, the mic pass-through is not affected/distorted, since it doesn't pass through the same playback-loop.
However, we could probably apply *some* of the effects (for example the `Radio Voice Effect` and `Clipping Effect` ones) to the mic passthrough output, since they are not dependent on the sender's position - all other distortions based on position/line of sight would not make sense to add locally though.

I'll keep this mind for a future update, can't promise an implementation yet though :+1:

**Comment by ciribob** [comment]
Implemented in next release 1.7.0.1
