### ISSUE TITLE
Create dark theme mode version

### ISSUE THREAD

**Issue by Dani3lNL** [ciribob/DCS-SimpleRadioStandalone#286]
Isn't it possible by just changing "BaseLight.xaml" into "BaseDark.xaml" in the App.xaml file? ("BaseDark.xaml" is a theme on https://mahapps.com/ as you can see there)

**Comment by MorpheusXAUT** [comment]
Sure, it's possible to change the theme, although there's a few other things that need to be changed beside that one line.
I personally prefer the light mode though (although I'm usually a big fan of dark mode, but those color schemes look a bit... off) and due to the way the SRS UI is currently set up, it's not a user selection, so we'd either have to switch completely (for everyone) or always compile two versions (which confuses people and the updater).

**Comment by Dani3lNL** [comment]
The weird thing is though that it doesn't even support Windows High Contrast mode (LAlt+LShift+PrntScreen). I thought that's an included function in every Visual compiled program that doesn't use DirectX ? @MorpheusXAUT  I think best would be a small "dark" button in some corner of the main window, which instantly (or on app restart) changes to dark, and also saves "darkMode = activated" in some .cfg file instantly when the player clicks it, so that when exiting and restarting the program (best even when closing the srs process in task manager, so that even when electricity fails it saved the mode status)

**Comment by MorpheusXAUT** [comment]
SRS does not use default styling provided by Windows/.NET, but a custom UI library (as you've already linked above). I honestly don't know if there's out-of-the-box support for high-contrast mode using that library, but even if there is, SRS is most likely not set up to utilise it properly.

As already mentioned, having a button/setting to switch it is not completely trivial due to the way the current styling is set up, it would require a few changes to be completely functional. Might be nice to have for a future release, but will definitely be a lower priority than other features/bugs for now.

Saving settings when force-closing a program via task manager (or if your power goes out) is not an option, since SRS is either instantly killed by Windows (without giving it enough time to save its settings, as it already does on exit) or, well, your power goes out and causes your whole PC to go powerless within a millisecond, not really leaving time for a clean exit/saving your settings 😉

**Comment by Dani3lNL** [comment]
Yeah all I meant was that the moment the user would click "dark" (mode), that value (boolean?) "DarkMode=true" gets saved in a .cfg file instantly, so that if power failes a few seconds later, the .cfg file is already saved/updated on the HDD/SSD with "dark mode enabled" for when user then restarts PC and starts SRS to instantly start SRS in dark mode :P (yes, fixing sound bug and getting ready for 15.5.0 release with the already pulled bookmark-hotfix is way more important xD )

**Comment by Dani3lNL** [comment]
Why closed, is this on the to-do list already? :) @ciribob
