### ISSUE TITLE
SRS 1.5.4.0 playing windows error sound when not connected to an SRS server while joining a DCS game server

### ISSUE THREAD

**Issue by Dani3lNL** [ciribob/DCS-SimpleRadioStandalone#288]
I hear a windows error sound everytime I do this and doubt that it's DCS.exe playing the sound, I believe the culprit is a tiny bug in SRS. Happened 2-3 times to me already.

**Comment by Dani3lNL** [comment]
(added "an" in title)

**Comment by MorpheusXAUT** [comment]
Can you get a recording of the sound you're talking about?
As already mentioned in your other issue #276 regarding some sounds being played, the only one SRS actively play is [this one](https://www.dropbox.com/s/9drucchbjpq8dt5/hand.mp3?dl=0) (example using Win10 default sounds), which is used as an indicator to signal an connection being established automatically.

**Comment by Dani3lNL** [comment]
Ok, to reproduce, one doesn't even need to restart DCS, just go back to DCS main menu, close and restart SRS (do not connect), click "multiplayer/server browser" in DCS, join BlueFlag. Then this is the sound SRS plays (mp3 video, recorded my speaker xD ):  https://drive.google.com/open?id=12Ctcy9zRzPvhOb_nkVm9soPZoICfyD-e

**Comment by Dani3lNL** [comment]
(double-click is me joining the DCS game server, just about 250-2000 ms later you hear that SRS error sound)

**Comment by MorpheusXAUT** [comment]
The behavior you describe is exactly the one I've mentioned - SRS plays an autoconnect-sound.
The sound you've recorded is definitely a Win7 sound though, Win10 has a different (default) sound scheme.
As mentioned, we're simply using one of the two sounds provided by Windows/.NET, in the default Win10 sound pack, 3/5 sound the same, 1 is silent and the other one is the one we use. Since I have no Win7 machine/soundpack to test it with, I can't tell what they'll sound like under different sound schemes. I've thrown together a quick'n'dirty program that simply plays the sounds available at: https://www.dropbox.com/s/ap4czfkhmei72re/SystemSounds.exe?dl=0
If you can download + run and record those sounds, we can check if there's a more fitting one.

**Comment by Dani3lNL** [comment]
my log only from today, 3.10. : https://pastebin.com/PCGUNAQY @MorpheusXAUT

**Comment by Dani3lNL** [comment]
@MorpheusXAUT it's exactly the "hands" sound in your SystemSounds.exe ! ! :)

**Comment by Dani3lNL** [comment]
So, as you can see, exactly the same one that you hear in my video above...

**Comment by MorpheusXAUT** [comment]
Sounds are different and customisable in the upcoming release.
