### ISSUE TITLE
add onPlayerEjectEvent (eject from aircraft) -> forceSetPlayerFrequency to 000 instead of 251.

### ISSUE THREAD

**Issue by Dani3lNL** [ciribob/DCS-SimpleRadioStandalone#291]
As in reality pilots who eject don't have a radio while falling from parachute, I hope we either can get players switched to 000 MHz so they can't hear 264 MHz anymore, as we currently can't even talk to 264 anymore once we ejected. (being able to listen but not reply is not intended, either listen+talk or none of the two)

**Comment by MorpheusXAUT** [comment]
If you eject from your aircraft, you will lose access to your radios after a second or two, automatically disabling any and all radio communications (since you will no longer be in any module anymore and thus will not have radios).
The behaviour you're describing is caused by e.g. the BlueFlag server returning you to the spectator list automatically when killed, plus the SRS server having spectator audio enabled (as it's also the case on BlueFlag).
This is therefore intended behaviour and not a bug.

**Comment by Dani3lNL** [comment]
So how about disabling spectator audio? All it does is confuse new players to thinking "why the *** can't anyone hear me? I'm transmitting... wtf" . What do you think about fully enabling it for let's say 30 seconds until after ejection? @MorpheusXAUT

**Comment by MorpheusXAUT** [comment]
Current implementation works as intended for its purpose

**Comment by Dani3lNL** [comment]
yes, it's a minor issue, but I'm sure most new players will be very confused by it. Your thought on this? @ciribob

**Comment by ciribob** [comment]
Its intended - as morpheus says

**Comment by Dani3lNL** [comment]
Still, it'd be way less confusing for new players to be either able to listen **&** talk for 30 seconds after ejecting, or **none** of the two.
