### ISSUE TITLE
IFF mode4 and mode 3/c

### ISSUE THREAD

**Issue by AndreaWez** [ciribob/DCS-SimpleRadioStandalone#306]
Is possible with srs set a virtual IFF system mode 3 and 4 due to comunicate with Lotatc or other SRS client? 
thanks

**Comment by thebgpikester** [comment]
+1

**Comment by 132ndNeck** [comment]
+1

**Comment by ciribob** [comment]
Are people still keen on this? 

Can you provide more info on how it works?

**Comment by ExoLightFR** [comment]
I'm super up on this ! What info do you need ?

**Comment by ciribob** [comment]
Anything and everything :)

What would you expect to see on SRS - assumedly some kind of button with 3 stage light, enemy, unknown, friendly?

Mode 3 and mode 6 info

How codes work etc

**Comment by AndreaWez** [comment]
i think we can use  Mode4 ( i don't know mod 6, is it a special mod of dcs?) .


Mod 4 (or Mod6) we can use a secret code, 4 digits i think is enough, when aicraft sets Mod4 on LotATC will be friendly or Enemy. if you are frliendly you can see  blue icon and the dcs tail number also, if you are enemy, red icon without dcs tail number.  

On DCS, the iff can be OFF (on lotATC you'll be unknow, no reply if someone interrogate you.  ON (shows info that i've spoke above and reply if someone interrogate you)

On SRS, a panel like overlay that already exists, where you have a code window,  3 lights, each light has a sound, a button that you can use to interrogate a contac.
window: a small window, like window radio frequency that we already have where can i set the secret code.
lights:
light 1 green - IFF request (someone ask you if you are Friendly or Foe) - play sound 3 short "bip"
light 2 blue and red - IFF Interrogate (if you interrogate someone if he is a Friendly or Foe) - 
reply friend: blue light  play 1 long higher "bip". reply enemy play 1 long low "bip"
light 3 orange - no reply, if you ask if someone is a Friendly or Foe but no reply received in 5 second (example). play dual tone short "bip"
Button:
 "IFF interrogate" that you can able to bind whit hotas button or simply click with mouse
to send a request if someone is a Friendly or Foe.

this is my idea, thank you :)

**Comment by ExoLightFR** [comment]
Well first of all, a disclaimer : I am in no way an expert in this, just a mere armchair pilot and civilian who happens to know some things about this and how to use Google. Take all of what I say with a grain of salt.

Now, about IFF : there are several modes of operation :
- **Mode 1** is an unsecured, two digit octal (ranges from 0 to 7) code that is set from the cockpit and allows to identify the coalition, aircraft, or mission. 
- **Mode 2** is an unsecured, 4 digit octal code that identifies the aircraft itself (or its tail number), kind of like a license plate. It is not changeable from the cockpit, only from the ground (except for some transport aircraft). 
- **Mode 3** is the most common type of IFF, since it is the one used in all civil aviation today. It is once again a 4 digit, unsecured, octal code and is set by the pilot according to what the ATC tells them, or if uncontrolled, according to local regulations. Mode 3 has two submodes in use today, mode 3/A and 3/C. The main difference is that mode 3/A responds to ATC’s secondary radar, but 3/C also transmits the aircraft flight level. The aircraft code, and if using mode 3/C, its flight level, are shown on the ATC’s radar screen. 

Note that modes 1, 2 and 3 are all unsecured. This introduces some problems : first of all, the enemy coalition could guess the good IFF codes, enter them into their transponders, and make the other coalition think they’re friendlies. This is solved by changing IFF codes depending on the time of the day, and sometimes to the position of the aircraft in the AO.
But there is another problem with this : as long as an interrogator broadcasts a valid interrogation request for a coalition, all of the transponders will respond. The other coalition could then triangulate their position.

- In answer to this problem, the west came up with the IFF Mk. XII, that introduced **mode 4**. It is a secure mode, set from the cockpit and works with two keys, A and B, that are often rotated according to the time of the day and position in the AO. In modern aircraft this is done automatically with a data cartridge. The way IFF mode 4 works and how it is different from the other modes is best explained by Wikipedia : 
> “Mode 4 started with an interrogation similar to Mode 3, but then followed that with an encoded pulse chain similar to the one used in Mode 3/A. The receiver side of the transponder checks this code against a known day code, and only responds if the two match. The pulses in the reply are delayed based on the received code. This largely eliminates the ability for the enemy to trigger the transponder.”

- As far as I know, **mode 5** is a more advanced mode 4, similar to civilian mode S and ADSB. I have absolutely no clue about what **mode 6** is, only that it seems to be working like mode 4, with two keys, and that it’s secured.

I think where the SRS IFF would be the most useful is in coordination with LotATC, if you guys can make it happen ; this way, not only could we have an IFF on our radar screen, we could see transponder codes, and then obviously interact with players around this, assign them codes, identify aircrafts based on IFF returns, see if one is squawking emergency, etc… That could add a lot of immersion.

Now, on the pilot with SRS side, I don’t think we can do much with the interrogator. The results of an IFF interrogation are supposed to show up on the radar screen/HSI on most planes, so that would, I believe, need ED’s work on the whole IFF system. On the transponder, however, if you can extract the IFF panel’s information just like you do with the radios, we could at least have M1, M3/A and M4 modeled on a lot of aircraft. 

[See this standard IFF panel, equipped in a lot of NATO aircraft.](https://live.staticflickr.com/5058/5534144940_a609df1b71_b.jpg) You’ll find it in many modules. On the bottom, the pilot can turn IFF M4 on or off, and set the M1 and M3/A codes. The “IDENT” switch allows the pilot to “squawk ident” : this makes his radar return flash on the ATC’s screen, which is used to attract his attention or at ATC’s request to find the pilot more easily. I don’t know what the “MIC” position does. 

Above this are 4 switches that are used to test and turn on or off the different modes (M1, M2, M3/A and M3/C). To their left is a 3 position switch that sets how the system signals to the pilot that the IFF couldn’t answer to a M4 interrogation properly : on “LIGHT” it triggers a light in the cockpit (not sure which one), on “AUDIO” it plays an audio cue, on “OUT” it doesn’t tell the pilot anything.

Above again are two knobs : the one on the left is to control whether M4 is using the A or B key, or to zeroize it (erasing the key to avoid it falling into enemy hands). The “HOLD” position saves the M4 key so it doesn’t automatically get erased upon shutdown. The knob on the right is the master knob. STBY powers the system, but doesn’t allow it to answer to IFF interrogations. The “LOW” position reduces the range at which the system responds to interrogations. “NORM” is normal operation. In “EMER”, the system will respond to interrogations with an code (I believe it is M1 : 70, M2 : 7777 and M3 7700 with M4 not changing, but I’m not certain about M1 and M2. M3 is for sure, it’s the same code as in civil aviation).

If SRS could extract these settings that would be set by the pilot in the cockpit (we could just use the overlay for aircraft that don’t have the IFF panel, just like FC3 radios), and have an integration with LotATC so the GCI could see the different transponder codes, that would be awesome ! The tricky part is with the AI : I don’t think DCS gives them transponder codes to be honest, only this famous magical IFF. I guess SRS would have to cheat, and just go for FC3 style IFF. If SRS can detect in which coalition an aircraft is on that shouldn’t be too much of a problem. 

Sorry for the extra long answer, I hope I answered to your questions ! I’m also on the SRS Discord if you need me there.

**Comment by ciribob** [comment]
Thanks for this - that's very helpful

I've had a chat to Dart too and will work on a proof of concept to get the mode info from SRS and export it in a format that LotATC can accept

**Comment by ExoLightFR** [comment]
That's very good news ! Thanks for your work.

**Comment by thebgpikester** [comment]
Couple of thoughts from someone that used UR's transponder sim and LotATC in a realism squadron in DCS.

You can use this even on public servers and even with FC3 level modules by setting a default Mode3 code in the unit name tag like Ciribob1-1 ~4550 to represent a default Mode3 tag that SRS could begin with, if the Mission designer wanted. And it would have no public gameplay detraction or required effort.

This "default" has benefits for LotATC even as it is, as they can have a list of codes and flights and see the location of the flight even if no more work was done over the top. A player on a public server with SRS may have absolutely no idea of IFF and the controller could locate them regardless and begin dialogue if they wished. Mode3 is quite flexible and MD's could set the defaults in ranges to assit further.

Mode4 encrypted can be set as default in ranges and be completely transparent and coalition specific, or editable by the MD also.

Interogations I dont know how the power setting affect... like line of sight etc but that's something that would need coded. I'm really not sure which modules can have active IFF interogation and how, the F-18 and F-16 do have a half reasonable simulation, like in straight lines. The Mirage appears to be a bit "wide".

It would mean a lot to many people to have this in game.

**Comment by ciribob** [comment]
I've had a talk with Dart - I won't implement interrogate initially, as it's it for FC3 and I'm not sure it adds much as the fc3 avionics already do it?

Replicating IFF Interrogate for non fc3 also doesn't seem a good idea as I can't get access to radar info for non fc3 

What I'll work on is a new panel to show the code and modes which is pulled from the cockpit or set manually for FC3

That'll be exported into lotatc and Dart can work his magic with it

**Comment by thebgpikester** [comment]
Yes you are right, you can't tell if someone is locked, or where the radar is pointed and even if you could the game will present more info to the cockpit avionics you can't touch. 

So your scope is just for LotATC, to provide codes back to it? Very generous if so! I can't think of many other ways to use this at the moment, so I guess good luck!

**Comment by ciribob** [comment]
Pretty much exactly that yes - just provide to LotATC. SRS has a server component that doesnt exist on UniversRadio which means the SRS server can provide all this info straight into the LotATC instance in a straightforward way - and all client data would be provided if they're on SRS 👍

**Comment by ciribob** [comment]
Some progress on Discord

![image](https://user-images.githubusercontent.com/786992/73613580-3b24f700-45ef-11ea-94b4-b88484ecfce6.png)

**Comment by ciribob** [comment]
implemented in #406 

LotATC adding support shortly 👍 

Thanks all!
