### ISSUE TITLE
Gazelle and 243.000 Frequency.

### ISSUE THREAD

**Issue by Forsaken-Player** [ciribob/DCS-SimpleRadioStandalone#316]
Steam Open BETA.
If I tune 243.000 frequency in the Gazelle, the overlay windows of SRS won't change. It does change if I enter any other frequency. But 243 won't.

https://youtu.be/WuonX861Nhg

**Comment by MorpheusXAUT** [comment]
Hi @Forsaken-Player ,
thanks for the report and the video, I'll try to reproduce this issue with a dev version during this weekend to figure out what could be causing this.

Just to confirm: you've not seen this behavior with any other radios of the Gazelle, correct?

**Comment by Forsaken-Player** [comment]
I didn't try other modules because I use Steam and the other one is in the DCS version that I uninstalled due being low on space. Sorry.

**Comment by MorpheusXAUT** [comment]
Sorry, I mean the other two (AM/FM) radios of the Gazelle, not different modules.

No worries, I'll just test all of the Gazelle ones during the weekend and see if I can reproduce the issue.

**Comment by Forsaken-Player** [comment]
Oh. I didn't read correctly the question. Sorry. I have to say I did not test it in other radios. They did work but in the freq I used. But that's not conclusive :)

**Comment by MorpheusXAUT** [comment]
:+1: I figured as much :smile: 
I'll primarily try to reproduce this issue in the next days, since it's shown pretty well in your video, but will try and see if I notice something similar for the other radios as well.

**Comment by MorpheusXAUT** [comment]
Was able to reproduce the issue with the Gazelle and I believe I have a partial explanation:

It looks like the radio ingame allows you to enter and display 3 digits after the decimal point, however rounds the last digit to the closest 0 or 5. For example, `233.332` gets rounded to `233.330`, but `233.333` gets rounded to `233.335` - same happens for `233.337` -> `233.335` and `233.338` -> `233.340`.
I assume this rounding happens due to some limitation in either radio or game engine capabilities, although it shouldn't be possible to enter those frequencies then, or they should at least update accordingly ingame and not differ from the values represented via the game's API.

While this explains the second weird behaviour you've encountered, I don't have a full explanation as to why you cannot tune to `243.000` once you've changed the frequency, I assume it might be a different issue since that's the default frequency this radio starts with (which also cannot be changed via mission editor, from what I've seen).

I'll continue to investigate and try to figure out what's causing this and will open a bug report if it indeed turns out to be a DCS/Gazelle issue.

Thanks for the find and report, definitely interesting to see!

**Comment by Forsaken-Player** [comment]
Thank you for your time and dedication to this wonderful app. 

May I ask if you have any information about internal in game voice/radio system? I hope both system can coexist. DCS have to do a lot of work if they want to improve the communications comparing to the capabilities of this great software.

Thanks again.

P.s. sorry about my weird English. :)

**Comment by MorpheusXAUT** [comment]
Are you talking about the new ingame voice system ED has announced on their roadmap? If so, no, sorry, we don't have any more information on that either 😄 

I did manage to reproduce and debug the issue on all Gazelle models now though, SRS simply receives no update from DCS when the frequency is changed to `243.000`. Will file a bug with Polychop 👍

**Comment by ciribob** [comment]
Fixed the rounding issue - other bug is with Polychop 👍 Thanks for the report!

**Comment by Forsaken-Player** [comment]
Hello, I was trying the Gazelle today. And 243.000 gets 243.001, if I dial 243.001 SRS will switch to 243.002.... it's clearer watching the video. https://youtu.be/nvAOOyYzlms

**Comment by ciribob** [comment]
Hmm will take another look

**Comment by ciribob** [comment]
Should be solved now - please reopen if not

Once you've tuned to anything other than 243.000 it is impossible to ever tune to just 243.000 again which is a module bug. 243.001 works fine!
