### ISSUE TITLE
JSON export - add server version

### ISSUE THREAD

**Issue by szporwolik** [ciribob/DCS-SimpleRadioStandalone#318]
Feature request:
I'd like to display running version of SRS at my squadron's website; would it be possible to add to the top level of JSON file the SRS's version running ?

Example from DARt's LotATC:
_"version": "1.1.2-bc9ac1b0"_

Thank you for consideration!

**Comment by MorpheusXAUT** [comment]
Are you talking about the client list exported by the server?
If so, I'd be a bit hesitant to add it to that since it'd require us to change the structure in a non-backward compatible way that'd require an update to everything that parses the file.
@ciribob your opinion on that? Maybe for the next larger release?

**Comment by szporwolik** [comment]
Correct "client-list" - no matter where in the JSON structure it will land, most important is to be able to see what version of SRS server generated the file.

**Comment by MorpheusXAUT** [comment]
Sorry for the long delay, `client-list.json` will include the server's version with 1.7.0.0 and upward (not included in current beta).

**Comment by ciribob** [comment]
Implemented in next release 1.7.0.1

**Comment by szporwolik** [comment]
@ciribob Thank you sir! This is exactly what was needed. :)
https://i.imgur.com/5rfuvup.png

**Comment by ciribob** [comment]
Glad to hear!
