### ISSUE TITLE
Feature Request: Allow Server Side to run Headless

### ISSUE THREAD

**Issue by razzun** [ciribob/DCS-SimpleRadioStandalone#333]
Allow the server side to run headless so that it can be run as a service (by using something similar to NSSM (Non-Sucking Service Manager)) or allowing it to run as a Schedule Task at system startup and not relying on someone to have to log into a system.

This would assist those that have the server on a dedicated machine and help limit interruptions due to system reboot (or power loss) and where auto login is not advisable (such as running it on AWS or Azure).

A simple way I would think of adding the headless feature would be to add a command line argument such as /silent or /nogui.  This would allow the server side to continue to function as is for those that are less tech savvy but give those that are more tech savvy an extra tool in running their servers from the command line.

**Comment by thebgpikester** [comment]
Since you can make any executable run as a service, what am I missing?

**Comment by razzun** [comment]
It won't run as a service due to the GUI needing to load.  It looks like it's running, but you can't connect at all.  The idea would be to run it as a background service, not something int he foreground.

**Comment by thebgpikester** [comment]
No anything with a gui should never be elevated to system, its a principal security design. Would require a pair of exes and redesign. Forgot this had a gui.

**Comment by ciribob** [comment]
New release will drop the requirement for Admin on the Server as its not required - but is on the client that should help

**Comment by atomicus** [comment]
While I generally favor the idea of being able to run it headless, need to ask a question here:
You can't run DCS headless, so  you need to make windows auto-login on startup to be able to run DCS itself.

Due to this critical;) limitation, you should be perfectly fine with running srs as a scheduled task, at least that's what we do on our servers. Both SRS and DCS are started as scheduled tasks (on user login).
If it's somehow not working as a scheduled task (you can't connect), then something else is wrong

**Comment by ciribob** [comment]
Closing for now as no plans in the immediate future

**Comment by gkleinfe** [comment]
I realize this is closed, but I'd like to add a couple things to hopefully increase the chances of this feature being added.

DCS Server can be installed as a service using nssm and pointing it to the DCS.exe file.  I'm also running Overlordbot on my server as a Windows service.  

Overlordbot requires me to enable EAM and assign a password to both coalition in SRS server.  This has to be done each time I run the SRS server as I cannot save my setting nor can I find a file that contains them to permanently change them.

What would be nice to see is the headless/no gui client where the settings can be configure in a file (ini, xml, json) so that I can launch it as a service but still change parameters as needed.  Razzun pointed out that the services will auto launch on server reboot due to power loss, maintenance, etc.
