### ISSUE TITLE
AWACS radio overlay EAM keeps switching between JSON and DCS radios

### ISSUE THREAD

**Issue by danvac** [ciribob/DCS-SimpleRadioStandalone#334]
AWACS radio overlay in external awacs mode keeps switching between JSON and DCS scripts defined radios.

Steps to reproduce:
1. create own awacs-radios.json configuration
2. connect to SRS server and open awacs overlay
3. connect external awacs mode
4. connect to DCS server
=> radio start switching between json config and internal config

Can be seen there: https://youtu.be/NTY9CDb3LDE

**Comment by MorpheusXAUT** [comment]
Hi,

Having both EAM connected and DCS running is not intended behaviour - EAM was added to use SRS without the need to run DCS (e.g. if you're just using LotATC).
May I ask why you're using both simultaneously?

That said, we should probably extend the EAM check to disable itself when a DCS connection has been made.

**Comment by Yskonyn** [comment]
In the 132nd we have ATC and AWACS separated, so a tower controller starts DCS to have a virtual overview of the airbase in the tower position, while still using LotATC as a ‘Terminal Radar’ kind of setup. 
It would be great if the two could be used simultaneously with SRS.

**Comment by danvac** [comment]
Also awacs-radios.json allows us to create predefined and named radios for all our ATC/AWACS people to share and it gets rewritten to default values when connected to DCS. @MorpheusXAUT so it may be other issue to make AWACS overlay configurable when connected to DCS? Or it's that already possible?

**Comment by MorpheusXAUT** [comment]
Sorry for the late reply, haven't had much time as of late.

@Yskonyn if you connect to DCS anyways to get an in-game view, you do not need to use the EAM since DCS will already grab your coalition info from the observer slot you've joined. I've also used a similar setup to yours before and I simply don't connect to EAM while DCS is running.

@danvac Unfortunately, the `awacs-radios.json` will be overwritten by DCS information due to how in-game information is handled, so you currently can't use that file if you also launch DCS. You could create predefined channels for the AWACS overlay radios (e.g. create a text file called `UHF Guard.txt` and add one frequency per line), however that's not exactly the same as your setup and wouldn't allow for custom radio naming either.
Maybe that's something to be supported in the future, however I'm afraid it's not possible at the moment and I can't give a timeframe either, sorry.
