### ISSUE TITLE
App crash with the KB4515384 Windows 10 update

### ISSUE THREAD

**Issue by MarcoJayUsai** [ciribob/DCS-SimpleRadioStandalone#344]
#### Issue description
SRS 1.6.2.0 Windows 10 Pro N 64 bit

Since the installation of the KB4515384 Windows 10 update (mandatory), whenever I try to open a dropdown menu the app crashes and exit. 

#### Steps to reproduce the issue

1. Install KB4515384 Windows 10 update on Windows 10 Pro N
2. Launch SRS and try to open microphone or favorites dropdown menu or any other dropdown in the Settings tab

#### What's the expected result?
- The app don't exit unexpectedly

#### What's the actual result?
- The app crashes and exit

#### Additional details / screenshot
[DxDiag.txt](https://github.com/ciribob/DCS-SimpleRadioStandalone/files/3682186/DxDiag.txt)

**Comment by MorpheusXAUT** [comment]
Thanks for the report, we've had multiple people who've had issues with some of the latest Windows 10 updates. Reinstalling the media pack has helped in many cases apparently, we're still trying to figure out what audio-related changes could be done on our side to avoid such crashes.

One thing confusing me is the crash on opening the favourites dropdown though, since that should have no relation to any potential audio issues. Can you reliably reproduce the crash when opening the favourites dropdown (e.g. also waiting for a minute or two after startup and only opening the favourites then)?

Unfortunately, neither of our dev PCs has received the mentioned KB yet, so we currently cannot attempt to reproduce the issue locally.

Does the `clientlog.txt` file in your SRS install directory contain anything useful by any chance?

**Comment by MarcoJayUsai** [comment]
It seems related to the dropdown gui element:

Also in the "Settings" tab, if I try to use any of the dropdowns to choose audio channel position (Left/Right/Both dropdown) the app crashes.

> Reinstalling the media pack has helped in many cases apparently, we're still trying to figure out what audio-related changes could be done on our side to avoid such crashes.

Thanks, I'll give a try to the media-pack reinstall

**Comment by MarcoJayUsai** [comment]
Just reinstalled the media feature pack, it didn't do the trick sadly.

**Comment by MarcoJayUsai** [comment]
Update: with Riva Tuner 7.2.2.20238 opened (even in the tray), the issue is happening.

The issue **does not** happen closing Riva Tuner 7.2.2.20238.

I'm gonna try now the latest version of Riva Tuner and report back

**Comment by ciribob** [comment]
Riva Tuner breaks .Net WPF programs as it trys to inject an FPS counter into the directx render of the UI and kills it and nothing I can work around

I think you can exclude on programs on Riva Tuner from the FPS counter

Will close for now but let me know if you have any update
