### ISSUE TITLE
Landing page for releases points to BETA version

### ISSUE THREAD

**Issue by thebgpikester** [ciribob/DCS-SimpleRadioStandalone#353]
https://github.com/ciribob/DCS-SimpleRadioStandalone/releases

Which is where people go to download SRS by default, points to an incompatible version 1.7 with the live version 1.6.4.

I think all beta versions especially those that have no backwards compatibility should not be "coming to the top" of availability where visible. To avoid confusion on compatibility.

**Comment by LazyBoot** [comment]
Suggestion: change the link to https://github.com/ciribob/DCS-SimpleRadioStandalone/releases/latest instead, that will auto-forward to the latest non-pre-release

**Comment by MorpheusXAUT** [comment]
Unfortunately, we cannot change the order on the releases page since it'll always put the newest version on top, which is why we mark it with `Pre-release` and `BETA` in the title.

As @LazyBoot mentioned though, using the `latest` release link (as we do for all our official posts and the client as well) will always redirect you to the latest *stable* release.

Closing for now as there's not much we can do due to the way GitHub works.
