### ISSUE TITLE
Multiple SRS clients with same physical IP

### ISSUE THREAD

**Issue by Couby** [ciribob/DCS-SimpleRadioStandalone#354]
Hi,

Trying to connect multiple SRS clients on a LAN to an online server, we have the issue of just one able to really connect the server. Seems to be a conflict, maybe cos using same physical (public) IP...

Would it be possible to fix such issue, as it is working fine with the DCS for exemple :blush: (multiple clients on a LAN with same physical IP joining an online session).

Best regards.

**Comment by ciribob** [comment]
Can you send the client logs of each machine? 

I test SRS by running multiple clients on a single machine so it will make no difference if they're behind a LAN or not - the only limitation is that each must be installed individually in order to generate a unique client ID

To make sure that is the case - uninstall SRS using the installer AND delete the entire folder in program files/DCS-SimpleRadioStandalone to clear the .cfg file that has the client ID

**Comment by Couby** [comment]
> the only limitation is that **each must be installed individually** in order to generate a unique client ID

Many thanks @ciribob . That surely is the point ❗️ 

I installed SRS on the LAN via copy paste of the folder...
Will check monday, but I'm nearly sure that's the problem.
