### ISSUE TITLE
1.8.0.1 - No comms possible when in JTAC slot

### ISSUE THREAD

**Issue by D4n2020** [ciribob/DCS-SimpleRadioStandalone#451]
Am in JTAC slot, on 126.00 AM, shows connected, but lacks the number that indicates how many others are tuned into 126.00. When switching to Su-25T, it's working flawless. Switched back to JTAC slot, not working again.

**Comment by ciribob** [comment]
Not able to replicate

https://gyazo.com/dc4d633ba3885523c0a67edcaf8dbe2f

**Comment by ciribob** [comment]
OK think i've replicated

The bug is that the side / coalition is only being sent in spectators or in an actual aircraft slot so GCI goes by the last sent coalition

If you go spectators -> GCI the coalition is stuck at spectators
If you go spectators -> aircraft -> GCI - the coalition will be correct and the same as the last aircraft you were in

I'll release a hotfix soon - only clientside
