### ISSUE TITLE
Gradually add more noise when dinstance increases or LOS is broken

### ISSUE THREAD

**Issue by obfuscoder** [ciribob/DCS-SimpleRadioStandalone#499]
At the moment the distance between sender and receive is simulated by reducing the volume of the signal until it is not heard at all. I would like to have a gradual increase in static noise added instead/as well to make it more realistic. See https://youtu.be/9Iv3Gz7XSKg

**Comment by Peliia** [comment]
I don't think your proposal is actually realistic, but that is based on my understanding of squelch.

The radio, when on, receives on its frequency constantly, so it constantly receives static. Squelch serves as a noise gate that pushes the noise floor to inaudible levels, and so only the key tones and actual transmission makes it through to the listener. As the distance increases, the reception strength approaches the noise floor, so since the difference between the noise floor and the transmit is less, with squelch applied, the transmit is quiet, but still without static, as the static is, well, static and always the same.

This is why there is a squelch switch, when reception is weak, you disable squelch to let the static in and hopefully make the transmit out in it.

**Comment by ciribob** [comment]
This is partially in now - the transmission will get quieter with LOS or Distance - the noise will be louder as a result if you enable all the new effects
