### ISSUE TITLE
Hotkeys

### ISSUE THREAD

**Issue by stvnpeters34** [ciribob/DCS-SimpleRadioStandalone#50]
Hey,

I am really sorry to say that its not worki
[clientlog.txt](https://github.com/ciribob/DCS-SimpleRadioStandalone/files/362902/clientlog.txt)
ng again.

**Comment by ciribob** [comment]
Hmm that's very odd.

Would you mind deleting the logs and trying to bind the keys again and then sending logs again?

I cant see the lines that should be there listing usb devices and which ones its listening too.

It should say something like found warthog, then adding warthog.

Sorry, really thought I'd cracked it! 

Are you trying to bind the warthog and do you use target?

**Comment by stvnpeters34** [comment]
I see what you are saying but its not catching anything.
[clientlog.txt](https://github.com/ciribob/DCS-SimpleRadioStandalone/files/364823/clientlog.txt)

**Comment by ciribob** [comment]
Very odd.... on the last try, did you try assigning keys as well?

I'll do a build for you tonight that adds more logging so we can see what's going on.

Sorry I've not managed to crack it!

What timezone are you in? I might be able to help you on TS on Saturday

**Comment by stvnpeters34** [comment]
I am in Eastern Standard Time

**Comment by ciribob** [comment]
Ok try the new version, it should log correctly again and then I will black list all your devices except the warthog!

Fingers crossed that'll be it :)

**Comment by stvnpeters34** [comment]
Here it is ciri
[clientlog.txt](https://github.com/ciribob/DCS-SimpleRadioStandalone/files/367345/clientlog.txt)

**Comment by ciribob** [comment]
Thanks! 
[SR-ClientRadio.zip](https://github.com/ciribob/DCS-SimpleRadioStandalone/files/367376/SR-ClientRadio.zip)

Try replacing the SR-ClientRadio.exe with the one in the zip and attached logs again.

This ignores all your devices so you should see it say Adding only for your Warthog Joystick and Throttle.

Try pressing Clear on all the binds as well before you try binding to clear the registry.

When assigning the Keys, make sure to hold them for a second or so as well so it has time to register.

Really hope this works otherwise i'm out of ideas! Sorry....

**Comment by stvnpeters34** [comment]
It works thank you soo much for all the help however are you gonna add this code to the new releases when they come out so i do not have this problem again

**Comment by ciribob** [comment]
Yes I'll add it :)
