### ISSUE TITLE
Audio channels are shifted in the UI

### ISSUE THREAD

**Issue by Nossarian** [ciribob/DCS-SimpleRadioStandalone#86]
I can't confirm at the moment, but I believe the Audio Channels have been shifted. The setting for Radio 1 is based on Radio 2, setting for Radio 2 is based on Radio 3, and the Setting for Radio 3 is based on Radio 1.

**Comment by ciribob** [comment]
ah yes its a silly off by one bug... Will be fixed in the next release :)

I've fixed internally but I'm going to try to get the Line of Sight done so it will be fixed in that update.

Currently in 1.1.8.0

Radio 1 Seperation controls Intercom
Radio 2 Seperation controls Radio 1
Radio 3 Seperation Controls Radio 2 + 3

**Comment by ciribob** [comment]
Also should have Line of Sight done by the weekend :+1:

**Comment by Nossarian** [comment]
What? It's not even my birthday; you shouldn't have!

Thanks for the updates!

**Comment by ciribob** [comment]
Dammit! I should've waited :p

**Comment by ciribob** [comment]
Fixed #89
